# TF
# TF plan and push and apply 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pr:
- ktpoc

resources:
- repo: self

pool:
  kt-devops-pool
  
steps:
  
- task: CmdLine@2
  displayName: Terraform Version
  inputs:
    script: 'terraform version' 

- task: CmdLine@2
  displayName: Terraform Init Delete
  inputs:
    script: 'rm -rf .terraform || true'

- task: CmdLine@2
  displayName: Terraform Init
  inputs:
    script: 'source /home/azureuser/terraform/ktpoc/init-terraform-ktpoc && terraform init'

- task: CmdLine@2
  displayName: Terraform Plan
  inputs:
    script: 'source /home/azureuser/terraform/ktpoc/init-terraform-ktpoc && terraform plan -out=tfplan'

- task: CmdLine@2
  displayName: Terraform Apply
  inputs:
    script: 'source /home/azureuser/terraform/ktpoc/init-terraform-ktpoc && terraform apply tfplan'